### ISSUE TITLE
Have to wait 30 seconds to use a wake word.

### ISSUE THREAD

**Issue by KerJoe** [Nailik/rhasspy_mobile#474]
While using "Porcupine (local)" for wake word recognition, after speech recording has completed and the intent is __successfully__ recognized and executed, I have to wait for approximately 30 seconds to be able to issue another wake word.

Here's what else I found:
* During the inactive period the "Wake Word" tab starts displaying "Pending" status.
* The last log line after recording is `{"tag":"WakeWordService","message":"startDetection false"'}`, the next line after the delay is `{"tag":"MqttService","message":"onMessageInternalReceived id 0 hermes/asr/stopListening"}` after that wake word becomes available.
* Manually sending `{"siteId": "mySiteId", "reason": "anything"}` to `/hermes/hotword/toggleOn` restores wake word functionality without the delay.

Log: [rhasspy_logfile_2023-08-15T13_49_04.271.json.txt](https://github.com/Nailik/rhasspy_mobile/files/12344906/rhasspy_logfile_2023-08-15T13_49_04.271.json.txt)
Settings: [org.rhasspy.mobile.android_preferences_export.xml.txt](https://github.com/Nailik/rhasspy_mobile/files/12344907/org.rhasspy.mobile.android_preferences_export.xml.txt)

Tested with 0.5.2-128 and nightly (0.5.2-130).

**Comment by KerJoe** [comment]
Yes, thank you. Changing the setting has indeed fixed the issue, now the wake word becomes available pretty much instantaneously.

Is it not possible to enable wake word detection after the local dialog manager has sent an action, regardless of the "changes via MQTT Api enabled" setting? If not, I think adding a warning about turning the option on while using the local dialog manager, should be sufficient.

**Comment by Nailik** [comment]
"Is it not possible to enable wake word detection after the local dialog manager has sent an action, regardless of the "changes via MQTT Api enabled" setting?"

- it does this but the setting enabled in the devices settings overrides the wake word service
- the dialog manager tells the wake word service to start and the wake word service determines if it really does according to this device setting and if microphone permission is given. 

The use case why i implemented it that way is the following
- user is watching tv and therefore wants hotword disabled -> sends mqtt message
- someone wakes rhasspy by using the button -> at the end of this session the dialog manager would override the device setting and therefore enable hotword even while tv is running. at thats the problem here.

will be closed by https://github.com/Nailik/rhasspy_mobile/issues/479

**Comment by KerJoe** [comment]
So does this mean that remotely disabling/enabling wake word recognition while using local dialog manager is not possible to accomplish (without suffering the delay)?

**Comment by Nailik** [comment]
You can simply use the http api [/api/listen-for-wake](https://github.com/Nailik/rhasspy_mobile/wiki/Http-Api#:~:text=/api/listen%2Dfor%2Dwake) or you can send the mqtt topic to the http api because it also knows all mqtt messages /api/mqtt/<topic>

**Comment by KerJoe** [comment]
Oh, OK then. Thanks again.

**Comment by Nailik** [comment]
https://github.com/Nailik/rhasspy_mobile/issues/479 done
